### ISSUE TITLE
Uncaught ReferenceError: file is not defined

### ISSUE THREAD

**Issue by FranzKnut** [PhilippImhof/tikz-preview#1]
[Enter steps to reproduce:]

I installed the package and got this error message when invoking "Show".
Also a preview field appears below the tikz specification displaying an endless loading animation.

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.14.6
**Thrown From**: [tikz-preview](https://github.com/PhilippImhof/tikz-preview) package 0.2.7

### Stack Trace

Uncaught ReferenceError: file is not defined

```
At /Users/julian/.atom/packages/tikz-preview/lib/tikz-preview.js:238

ReferenceError: file is not defined
    at /packages/tikz-preview/lib/tikz-preview.js:238:53
    at String.replace (<anonymous>)
    at Object.fetchPreamble (/packages/tikz-preview/lib/tikz-preview.js:237:25)
    at Object.showPreview (/packages/tikz-preview/lib/tikz-preview.js:262:25)
    at HTMLElement.tikzPreviewShow (/packages/tikz-preview/lib/tikz-preview.js:24:39)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350265)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348740)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:727465)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:735388)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
  2x -2:17.6.0 tikz-preview:show (input.hidden-input)
     -1:49.6.0 core:backspace (input.hidden-input)
  2x -0:18.4.0 core:move-up (input.hidden-input)
     -0:17.7.0 core:backspace (input.hidden-input)
     -0:04.4.0 tikz-preview:show (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.9.1 
color-picker 2.3.0 
compare-files 0.8.1 
copy-as-rtf 0.9.3 
copy-with-style 1.1.0 
highlight-selected 0.17.0 
hix 0.1.0 
intel-hex 0.1.0 
kite 0.178.0 
language-common-lisp 0.9.5 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-in-app 1.0.1 
open-recent 5.0.0 
open-terminal-here 2.3.2 
open-unsupported-files 1.0.20 
pdf-view 0.72.0 
pdf-view-plus 1.11.0 
pigments 0.40.2 
plantuml-toolkit 0.2.0 
Sublime-Style-Column-Selection 1.7.5 
tikz-preview 0.2.7 
todo-show 2.3.2 
```

**Comment by PhilippImhof** [comment]
Thanks for that report. I have an idea where this might come from, but I will need more information in order to narrow down the problem. Were you working with a previously saved file or was it a "new file" (e.g. no filename yet) in an editor tab? If it was a file, what was its name and path? Was it a multi-file document (e.g. one with a master file and several `\include`s) or just a single file on its own?

What contents were you trying to preview? Does it work when you just copy those contents (and the relevant part of the preamble) into a new document? Do you have `\input` directives in your preamble? If yes, what files are you `\input`ing, e.g. files in the same directory or from another directory, absolute or relative paths?

Did you see a warning or error message before the actual stack trace?

**Comment by FranzKnut** [comment]
> Were you working with a previously saved file or was it a "new file" (e.g. no filename yet) in an editor tab? 

A previously saved file

> If it was a file, what was its name and path? 

~/Desktop/movie/tw.tikz or ~/Desktop/movie/frame.tex
(I tried it with the external tikz file using \input and also with the tikz statements in the main tex file)

> Was it a multi-file document (e.g. one with a master file and several \includes) or just a single file on its own?

Just using \input but some style specs originate from another file like this:

`\tikzset{%
nstyle0/.style={fill=ngreen!1!ngray},
nstyle1/.style={fill=ngreen!1!ngray},
...
}
`

> What contents were you trying to preview? 

Some Graph having different colors for all edges and vertices. Hence the use of \tikzset.

> Does it work when you just copy those contents (and the relevant part of the preamble) into a new document? 

No I do get a different error: `Package pgfkeys Error: I do not know the key '/tikz/nstyle0' and I am going to ignore it. Perhaps you misspelled it.`

> Do you have \input directives in your preamble? If yes, what files are you \inputing, e.g. files in the same directory or from another directory, absolute or relative paths?

The files containing the tikz styles are in the same directory.

> Did you see a warning or error message before the actual stack trace?

No

**Comment by PhilippImhof** [comment]
Thanks for reporting the problem. It is now fixed.
